//
//  MyStrings.swift
//  MRConnectDemoProject
//
//  Created by Ansh Bangia on 31/01/22.
//

import Foundation

extension String {
    func localize() -> String {
        return NSLocalizedString(self, tableName: "Localizable", bundle: .main, value: self, comment: self)
    }
}

struct MyStrings {
    
    static let email = "email".localize()
    static let password = "password".localize()
    static let mr = "MR"
    static let doctor = "Doctor".localize()
    static let name = "name".localize()
    static let contact = "contact".localize()
    static let licenseNumber = "license number".localize()
    static let mrNumber = "MR number".localize()
    static let specialization = "specialization".localize()
    static let meetings = "Meetings".localize()
    static let doctors = "Doctors".localize()
    static let medicines = "Medicines".localize()
    static let profile = "Profile".localize()
    static let company = "company".localize()
    static let composition = "composition".localize()
    static let price = "price".localize()
    static let form = "form".localize()
    static let capsule = "Capsule".localize()
    static let tablet = "Tablet".localize()
    static let syrup = "Syrup".localize()
    static let injection = "Injection".localize()
    static let loginUpperCase = "LOG IN".localize()
    static let newUserSignUp = "New User? SIGN UP".localize()
    static let invalidEmailOrPass = "Invalid Email or Password.".localize()
    static let checkCredentials = "Please check your credentials.".localize()
    static let emptyFieldAlertTitle = "The |#X#| field cannot be empty.".localize()
    static let emptyFieldAlertSubtitle = "Please fill your |#X#|.".localize()
    static let signup = "Sign Up".localize()
    static let usertype = "User Type".localize()
    static let confirmPass = "confirm password".localize()
    static let invalidEmail = "Invalid Email".localize()
    static let enterValidEmail = "Please enter a valid email address.".localize()
    static let passNeeds6Char = "Password needs to be atleast 6 characters long.".localize()
    static let enter6Char = "Enter atleast 6 characters.".localize()
    static let confirmPassNotMatch = "Confirmed Password does not match.".localize()
    static let reenterConfirmPass = "Re-eneter confirmed password.".localize()
    static let signupUnsuccess = "Sign Up unsuccessful.".localize()
    static let tryDiffEmail = "Try a different email.".localize()
    static let companyName = "Company: |#X#|".localize()
    static let createMed = "Create Medicine".localize()
    static let medName = "medicine name".localize()
    static let create = "Create".localize()
    static let createUnsuccess = "|#X#| was not created successfully.".localize()
    static let tryAgain = "Please try again.".localize()
    static let cardiologist = "Cardiologist".localize()
    static let dermatologist = "Dermatologist".localize()
    static let gynecologist = "Gynecologist".localize()
    static let neurologist = "Neurologist".localize()
    static let oncologist = "Oncologist".localize()
    static let pediatrician = "Pediatrician".localize()
    static let physician = "Physician".localize()
    static let psychiatrist = "Psychiatrist".localize()
    static let radiologist = "Radiologist".localize()
    static let surgeon = "Surgeon".localize()
    static let done = "Done".localize()
    static let chooseSpec = "Choose your Specialization".localize()
    static let search = "Search".localize()
    static let add = "Add".localize()
    static let edit = "Edit".localize()
    static let imageNotChosen = "Image was not chosen.".localize()
    static let errorImage = "An error occurred while choosing image.".localize()
    static let changeName = "Change Name".localize()
    static let editName = "Edit your name".localize()
    static let newName = "new name".localize()
    static let newPassword = "new password".localize()
    static let confirmNewPass = "confirm new password".localize()
    static let changePassword = "Change Password".localize()
    static let enterNewPass = "Enter new password".localize()
    static let askChangePass = "Are you sure you want to change password?".localize()
    static let confirm = "Confirm".localize()
    static let cancel = "Cancel".localize()
    static let invalidPassword = "Invalid Password".localize()
    static let proceed = "Proceed".localize()
    static let enterOldPass = "Enter old password".localize()
    static let logOut = "Log Out".localize()
    static let createMeeting = "Create Meeting".localize()
    static let titleAndDesc = "Title and Description".localize()
    static let meetingTitle = "Meeting title".localize()
    static let meetingDescription = "Meeting description".localize()
    static let dateAndTime = "Date and Time".localize()
    static let date = "Date".localize()
    static let time = "Time".localize()
    static let selectDoctors = "Select Doctors".localize()
    static let selectMedicines = "Select Medicines".localize()
    static let noSelectionAlertTitle = "No |#X#| was selected.".localize()
    static let noSelectionAlertSubtitle = "Please select atleast one |#X#|.".localize()
    static let meeting = "Meeting".localize()
    static let medicine = "Medicine".localize()
    static let withLabel = "with: |#X#|".localize()
    static let editMeeting = "Edit Meeting".localize()
    static let notUpdatedTitle = "|#X#| was not updated.".localize()
    static let notUpdatedSubtitle = "An error occurred while updating |#X#|.".localize()
    static let noDescription = "No Description".localize()
    static let host = "Host".localize()
    static let today = "Today".localize()
    static let startTime = "Start Time".localize()
    static let endTime = "End Time".localize()
    static let invalidTime = "Invalid meeting time selected".localize()
    static let againApptTime = "Select appropriate meeting time.".localize()
    static let updateContact = "Update Contact".localize()
    static let updateYourContact = "Update your contact".localize()
    static let dispContact = "Contact: |#X#|".localize()
    static let office = "Current Office".localize()
    static let quali = "Qualification".localize()
    static let exp = "Work Experience".localize()
    static let addOffice = "Add current working location".localize()
    static let addQuali = "Add qualification".localize()
    static let addExp = "Add prior work experience".localize()
    static let notSpecified = "Not specified".localize()
    static let minsRemaining = "In |#X#| minutes".localize()
    static let minRemaining = "In |#X#| minute".localize()
    static let inProgress = "In progress".localize()
    static let recordMeeting = "Record Meeting".localize()
    static let stop = "Stop".localize()
    static let noMic = "Microphone permission not granted.".localize()
    static let enableMic = "Give access to microphone.".localize()
    static let askSaveRecording = "Save Recording?".localize()
    static let confirmSaveRecording = "Do you want to save the recording?".localize()
    static let yes = "Yes".localize()
    static let discard = "Discard".localize()
    static let recording = "Recording".localize()
    static let notSavedTitle = "|#X#| was not saved.".localize()
    static let notSavedSubtitle = "An error occurred while saving |#X#|.".localize()
    static let errorIn = "There was an erro in |#X#|.".localize()
    static let meetingOver = "Meeting over".localize()
    static let recordings = "Recordings".localize()
    static let error = "Error".localize()
    static let fileNotFound = "File not found".localize()
    static let noMeds = "No Medicines".localize()
    static let noDocs = "No Doctors".localize()
    static let noMeetings = "No Meetings".localize()
    static let loggingIn = "Logging In".localize()
    static let networkError = "Network Error".localize()
    static let errorOccured = "An error occured".localize()
    static let signingUp = "Signing Up".localize()
    
}
